### ISSUE TITLE
Problème d'installation de dashboards_store

### ISSUE THREAD

**Issue by AlimuratDinch** [Sciance-Inc/core.dashboards_store#38]
## Problem
Bonjour, 

J'ai deux problèmes avec l'installation de `dashboards_store`  en suivant la documentation.

Le premier problème concerne la commande `poetry install`. Il n'installe pas `core.data.store (0.9.0)` en disant

```
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: core.data.store (0.9.0)
The current project could not be installed: No file/folder found for package core.data.store
If you do not want to install the current project use --no-root
```
Cette commande crée l'environnement `(core-data-store-py3.10)`
Ma version de `poetry` est `1.7.1` et la version de `python` est `3.10.12`
 <br/>
Mon deuxième problème,  dans le dossier `working_directory`, quand j'essaye de copier le dossier de `core.dashboards_store` à `cssxx.dashboards_store` comme `child class` avec `cookiecutter` avec la commande:
```
cookiecutter core.dashboards_store/tooling/template
```
Il me demande pour `author`, `css_short_name`, `server_ip `et `server_port`. Je sais qu'ils sont écrits dans `github.com/Sciance-Inc/core.dashboards_store/blob/develop/tooling/template/cookiecutter.json` mais, il ne me demande pas le mot de passe à renseigner pour les futures opérations.
Dans la documentation, il dit que pendant l'opération de cookiecutter, le mot de passe aurait dû être demandé durant cette  étape.
Dans la documentation, il me dit de remplacer `password: dontLookAtMeImSecret`  dans `~/.dbt/profiles.yml` par le mot de passe qui était demandé pendant l'opération de `cookiecutter`.

Donc mes questions sont:
1) Est-ce que c'est normal que `core.data.store (0.9.0)` ne peut pas être installé.
2) Quel mot de passe je dois utiliser dans le fichier `~/.dbt/profiles.yml` pour connecter à la base de données?

Merci beaucoup 

## What have you tried so far ?
J'ai essayé de changer `name ([tool.poetry])`dans le fichier `pyproject.toml` à `core.data_store`, `core-data-store` et `core_data_store`, mais ça ne résout pas le problème avec `poetry install`

**Comment by hugoJuhel** [comment]
Bonjour @AlimuratDinch 

Tl;dr :
•	Il faut utiliser poetry install –no-root, comme indiqué dans le message d’erreur.
•	Il faut demander le mot de passe aux personnes ayant créé la base de données « store ».

Question 1 : poetry install
•	Core.dashboards_store utilise DBT, qui est lui-même programmé en Python.
•	Core.dashboards_store utilise poetry comme gestionnaire de dépendances python.
•	En plus d’être un gestionnaire de dépendances, poetry essaye aussi d’être aussi un gestionnaire de paquets, à l’instar de setuptools (cf PEP 518, PEP 621)
•	L’aspect gestionnaire de paquets de Poetry s’est accentué depuis la version 1.6.
•	Le rationnel est que les gens qui utilisent Poetry, s’en servent pour développer des projets eux-mêmes écrits en Python. Ce n’est cependant pas notre cas.
•	Lorsque l’on tape : poetry install, poetry essaye de faire deux choses :
o	1) installer les dépendances requises pour le projet (toutes les versions de Poetry)
o	2) installer le projet en lui-même (versions >= 1.6)
•	Dans notre cas, nous n’avons pas de projet à installer, nous nous servons uniquement du gestionnaire de dépendances. 
•	Lorsque vous entrez la commande poetry install, les logs indiquent :
o	Que la première étape s’est bien passé « No dependencies to install or update »
o	Que la seconde s’est mal passée… ce qui est logique. 
•	Poetry te propose donc d’utiliser la commande poetry install –no-root, afin de n’exécuter que la première partie. 
•	C’est parfaitement normal dans ce cas là. La doc n’a pas encore été mise-à jour suit à la dernière version de poetry.

Question 2 : mot de passe :
•	J’ai commis une erreur en écrivant la documentation, le mot de passe n’est effectivement jamais demandé (au moment de le programmer, j’ai pensé que les gens allaient préférer copier le mot de passe manuellement plutôt que de le faire dans un logiciel qu’ils ne maîtrisent pas). Je vais aller mettre à jour la documentation. 
•	Comme indiqué [ici](https://docs.dashboards-store.sciance.ca/installation/dbt-profile#got-it-i-need-a-profile-can-you-help-me-get-started), il faut :
o	1) manuellement ajouter le mot de passe de la base de données dans le fichier cssXX.dashboards_store/profiles-sample.yml
o	2) déplacer le fichier profiles-sample.yml dans ~/.dbt/profiles.yml
•	Le mot de passe à renseigner est le mot de passe à utiliser pour se connecter à la base de données dans laquelle seront matérialisées les données du comptoir.
•	Il m’est cependant impossible de vous donner ce mot de passe, car je n’ai pas créé la base de données / les usagers dans votre CSS.
